"""Utilities for TypeScript export generation."""

from __future__ import annotations

import json
from dataclasses import dataclass
from typing import Dict, Mapping, Optional

from .helpers import apply_prefix, ensure_extension

RARITY_OPTIONS = [
    ("(omit)", None),
    ("1 - Common", "1"),
    ("2 - Uncommon", "2"),
    ("3 - Rare", "3"),
    ("4 - Epic", "4"),
    ("5 - Mythic", "5"),
]

SPRITE_MODE_CUSTOM = "Exported art (custom filenames)"
SPRITE_MODE_BASE = "Reuse base game sprites"


@dataclass
class ExportOpts:
    skin_name: str
    lore: str
    rarity: Optional[str]
    noDropOnDeath: bool
    noDrop: bool
    ghillie: bool
    obstacleType: str
    baseScale: float
    lootBorderOn: bool
    lootBorderName: str
    lootBorderTint: str
    lootScale: float
    soundPickup: str
    ref_ext: str
    front_enabled: bool = False
    front_pos_x: int = 0
    front_pos_y: int = 0
    front_above_hand: bool = False

    def ts_block(self, ident: str, filenames: Mapping[str, str], tints: Mapping[str, str]) -> str:
        lines = ["// Generated by the Zurviv.io Skin Creator", ""]
        lines.append(f'export const {ident} = defineOutfitSkin("outfitBase", {{')
        lines.append(f'  name: {json.dumps(self.skin_name)},')
        if self.noDropOnDeath:
            lines.append('  noDropOnDeath: true,')
        if self.noDrop:
            lines.append('  noDrop: true,')
        if self.rarity:
            lines.append(f'  rarity: {self.rarity},')
        if self.lore:
            lines.append(f'  lore: {json.dumps(self.lore)},')
        if self.ghillie:
            lines.append('  ghillie: true,')
        if self.obstacleType:
            lines.append(f'  obstacleType: {json.dumps(self.obstacleType)},')
        if abs(self.baseScale - 1.0) > 1e-6:
            lines.append(f'  baseScale: {self.baseScale},')

        lines.append('  skinImg: {')
        lines.append(f'    baseTint: {tints["base"]},')
        lines.append(f'    baseSprite: "{filenames["base"]}",')
        lines.append(f'    handTint: {tints["hand"]},')
        lines.append(f'    handSprite: "{filenames["hands"]}",')
        lines.append(f'    footTint: {tints["foot"]},')
        lines.append(f'    footSprite: "{filenames["feet"]}",')
        lines.append(f'    backpackTint: {tints["backpack"]},')
        lines.append(f'    backpackSprite: "{filenames["backpack"]}",')
        if filenames.get("front"):
            if tints.get("front"):
                lines.append(f'    frontTint: {tints["front"]},')
            lines.append(f'    frontSprite: "{filenames["front"]}",')
            lines.append(
                f'    frontSpritePos: {{ x: {self.front_pos_x}, y: {self.front_pos_y} }},'
            )
            if self.front_above_hand:
                lines.append("    aboveHand: true,")
        lines.append('  },')

        lines.append('  lootImg: {')
        lines.append(f'    sprite: "{filenames["loot"]}",')
        lines.append(f'    tint: {tints["loot"]},')
        if self.lootBorderOn and filenames.get("border"):
            lines.append(f'    border: "{filenames["border"]}",')
            lines.append(f'    borderTint: {tints["border"]},')
            lines.append(f'    scale: {self.lootScale},')
        lines.append('  },')

        if self.soundPickup:
            lines.append('  sound: {')
            lines.append(f'    pickup: {json.dumps(self.soundPickup)},')
            lines.append('  },')

        lines.append('});')
        return "\n".join(lines)


def final_name(
    key: str,
    custom_stub: str,
    sprite_mode: str,
    existing_sprite_ids: Mapping[str, str],
    custom_dirs: Mapping[str, str],
    ext_ref: str,
) -> str:
    """Resolve the final sprite filename based on the configured strategy."""
    stub_with_ext = ensure_extension(custom_stub, ext_ref)
    if sprite_mode == SPRITE_MODE_BASE:
        existing = existing_sprite_ids.get(key, "")
        if existing:
            return ensure_extension(existing, ext_ref)
        return stub_with_ext
    if sprite_mode == SPRITE_MODE_CUSTOM:
        if key in {"base", "hands", "feet", "backpack", "front"}:
            return apply_prefix(custom_dirs.get("player", ""), stub_with_ext)
        if key in {"loot", "border", "inner"}:
            return apply_prefix(custom_dirs.get("loot", ""), stub_with_ext)
    return stub_with_ext


def build_filenames(
    base_id: str,
    sprite_mode: str,
    existing_sprite_ids: Mapping[str, str],
    custom_dirs: Mapping[str, str],
    ext_ref: str,
    loot_border_on: bool,
    loot_border_name: str,
    loot_inner_name: str,
    include_front: bool = False,
    front_stub: str = "",
) -> Dict[str, str]:
    filenames = {
        "base": final_name("base", f"player-base-{base_id}", sprite_mode, existing_sprite_ids, custom_dirs, ext_ref),
        "hands": final_name("hands", f"player-hands-{base_id}", sprite_mode, existing_sprite_ids, custom_dirs, ext_ref),
        "feet": final_name("feet", f"player-feet-{base_id}", sprite_mode, existing_sprite_ids, custom_dirs, ext_ref),
        "backpack": final_name("backpack", f"player-circle-base-{base_id}", sprite_mode, existing_sprite_ids, custom_dirs, ext_ref),
        "loot": final_name("loot", f"loot-shirt-outfit{base_id}", sprite_mode, existing_sprite_ids, custom_dirs, ext_ref),
        "border": "",
        "inner": "",
        "front": "",
    }
    if loot_border_on and loot_border_name:
        filenames["border"] = final_name("border", loot_border_name, sprite_mode, existing_sprite_ids, custom_dirs, ext_ref)
    if loot_border_on and loot_inner_name:
        filenames["inner"] = final_name("inner", loot_inner_name, sprite_mode, existing_sprite_ids, custom_dirs, ext_ref)
    if include_front and front_stub:
        filenames["front"] = final_name("front", front_stub, sprite_mode, existing_sprite_ids, custom_dirs, ext_ref)
    return filenames


def adjust_tints_for_sprite_mode(tints: Mapping[str, str], sprite_mode: str) -> Dict[str, str]:
    if sprite_mode != SPRITE_MODE_CUSTOM:
        return dict(tints)
    adjusted = {}
    for key, value in tints.items():
        adjusted[key] = "0xffffff" if value else value
    return adjusted


def build_manifest(
    ident: str,
    opts: ExportOpts,
    filenames: Mapping[str, str],
    ui_tints: Mapping[str, str],
    export_tints: Mapping[str, str],
    sprite_mode: str,
    preview_preset: str,
    front_meta: Optional[Dict[str, object]] = None,
    preview_options: Optional[Dict[str, object]] = None,
    export_format: str = "svg",
    export_files: Optional[Mapping[str, str]] = None,
) -> str:
    """Return a JSON manifest describing exported assets."""

    sprite_files = {key: value for key, value in filenames.items() if value}
    exported_files = {
        key: value for key, value in (export_files or {}).items() if value
    }

    front_meta = front_meta or {}

    preview_info = {"preset": preview_preset}
    if preview_options:
        preview_info.update(preview_options)

    manifest = {
        "skin": {
            "ident": ident,
            "name": opts.skin_name,
            "lore": opts.lore or None,
            "rarity": opts.rarity,
            "flags": {
                "noDropOnDeath": opts.noDropOnDeath,
                "noDrop": opts.noDrop,
                "ghillie": opts.ghillie,
            },
            "obstacleType": opts.obstacleType or None,
            "baseScale": opts.baseScale,
            "sound": opts.soundPickup,
        },
        "sprites": {
            "mode": sprite_mode,
            "referenceExtension": opts.ref_ext,
            "exportFormat": export_format.lower(),
            "files": sprite_files,
            "exportFiles": exported_files,
        },
        "tints": {
            "ui": dict(ui_tints),
            "export": dict(export_tints),
        },
        "loot": {
            "borderEnabled": opts.lootBorderOn,
            "borderSprite": sprite_files.get("border"),
            "borderTint": export_tints.get("border"),
            "innerSprite": sprite_files.get("inner"),
            "scale": opts.lootScale,
        },
        "preview": preview_info,
        "front": {
            "enabled": bool(front_meta.get("enabled")),
            "sprite": sprite_files.get("front"),
            "tint": export_tints.get("front"),
            "pos": {
                "x": front_meta.get("pos_x", opts.front_pos_x),
                "y": front_meta.get("pos_y", opts.front_pos_y),
            },
            "aboveHand": front_meta.get("aboveHand", opts.front_above_hand),
            "overlayAboveFront": front_meta.get("overlayAboveFront"),
        },
    }

    return json.dumps(manifest, indent=2, sort_keys=True) + "\n"


__all__ = [
    "ExportOpts",
    "RARITY_OPTIONS",
    "SPRITE_MODE_BASE",
    "SPRITE_MODE_CUSTOM",
    "adjust_tints_for_sprite_mode",
    "build_filenames",
    "build_manifest",
    "final_name",
]
